/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as IndexRouteImport } from './routes/index';
import { Route as SettingsRouteImport } from './routes/settings';
import { Route as OverviewNamespacesRouteImport } from './routes/overview/namespaces';
import { Route as OverviewNodesRouteImport } from './routes/overview/nodes';
import { Route as OverviewSummaryRouteImport } from './routes/overview/summary';
import { Route as OverviewNodesNameRouteImport } from './routes/overview/nodes_.$name';
import { Route as WorkloadsAutoscalersIndexRouteImport } from './routes/workloads/autoscalers/index';
import { Route as WorkloadsCronjobsIndexRouteImport } from './routes/workloads/cronjobs/index';
import { Route as WorkloadsDaemonsetsIndexRouteImport } from './routes/workloads/daemonsets/index';
import { Route as WorkloadsDeploymentsIndexRouteImport } from './routes/workloads/deployments/index';
import { Route as WorkloadsJobsIndexRouteImport } from './routes/workloads/jobs/index';
import { Route as WorkloadsPodsIndexRouteImport } from './routes/workloads/pods/index';
import { Route as WorkloadsStatefulsetsIndexRouteImport } from './routes/workloads/statefulsets/index';
import { Route as WorkloadsAutoscalersNamespaceNameRouteImport } from './routes/workloads/autoscalers/$namespace.$name';
import { Route as WorkloadsCronjobsNamespaceNameRouteImport } from './routes/workloads/cronjobs/$namespace.$name';
import { Route as WorkloadsDaemonsetsNamespaceNameRouteImport } from './routes/workloads/daemonsets/$namespace.$name';
import { Route as WorkloadsDeploymentsNamespaceNameRouteImport } from './routes/workloads/deployments/$namespace.$name';
import { Route as WorkloadsJobsNamespaceNameRouteImport } from './routes/workloads/jobs/$namespace.$name';
import { Route as WorkloadsPodsNamespaceNameRouteImport } from './routes/workloads/pods/$namespace.$name';
import { Route as WorkloadsStatefulsetsNamespaceNameRouteImport } from './routes/workloads/statefulsets/$namespace.$name';

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any);
const OverviewNamespacesRoute = OverviewNamespacesRouteImport.update({
  id: '/overview/namespaces',
  path: '/overview/namespaces',
  getParentRoute: () => rootRouteImport,
} as any);
const OverviewNodesRoute = OverviewNodesRouteImport.update({
  id: '/overview/nodes',
  path: '/overview/nodes',
  getParentRoute: () => rootRouteImport,
} as any);
const OverviewSummaryRoute = OverviewSummaryRouteImport.update({
  id: '/overview/summary',
  path: '/overview/summary',
  getParentRoute: () => rootRouteImport,
} as any);
const OverviewNodesNameRoute = OverviewNodesNameRouteImport.update({
  id: '/overview/nodes_/$name',
  path: '/overview/nodes/$name',
  getParentRoute: () => rootRouteImport,
} as any);
const WorkloadsAutoscalersIndexRoute =
  WorkloadsAutoscalersIndexRouteImport.update({
    id: '/workloads/autoscalers/',
    path: '/workloads/autoscalers/',
    getParentRoute: () => rootRouteImport,
  } as any);
const WorkloadsCronjobsIndexRoute = WorkloadsCronjobsIndexRouteImport.update({
  id: '/workloads/cronjobs/',
  path: '/workloads/cronjobs/',
  getParentRoute: () => rootRouteImport,
} as any);
const WorkloadsDaemonsetsIndexRoute =
  WorkloadsDaemonsetsIndexRouteImport.update({
    id: '/workloads/daemonsets/',
    path: '/workloads/daemonsets/',
    getParentRoute: () => rootRouteImport,
  } as any);
const WorkloadsDeploymentsIndexRoute =
  WorkloadsDeploymentsIndexRouteImport.update({
    id: '/workloads/deployments/',
    path: '/workloads/deployments/',
    getParentRoute: () => rootRouteImport,
  } as any);
const WorkloadsJobsIndexRoute = WorkloadsJobsIndexRouteImport.update({
  id: '/workloads/jobs/',
  path: '/workloads/jobs/',
  getParentRoute: () => rootRouteImport,
} as any);
const WorkloadsPodsIndexRoute = WorkloadsPodsIndexRouteImport.update({
  id: '/workloads/pods/',
  path: '/workloads/pods/',
  getParentRoute: () => rootRouteImport,
} as any);
const WorkloadsStatefulsetsIndexRoute =
  WorkloadsStatefulsetsIndexRouteImport.update({
    id: '/workloads/statefulsets/',
    path: '/workloads/statefulsets/',
    getParentRoute: () => rootRouteImport,
  } as any);
const WorkloadsAutoscalersNamespaceNameRoute =
  WorkloadsAutoscalersNamespaceNameRouteImport.update({
    id: '/workloads/autoscalers/$namespace/$name',
    path: '/workloads/autoscalers/$namespace/$name',
    getParentRoute: () => rootRouteImport,
  } as any);
const WorkloadsCronjobsNamespaceNameRoute =
  WorkloadsCronjobsNamespaceNameRouteImport.update({
    id: '/workloads/cronjobs/$namespace/$name',
    path: '/workloads/cronjobs/$namespace/$name',
    getParentRoute: () => rootRouteImport,
  } as any);
const WorkloadsDaemonsetsNamespaceNameRoute =
  WorkloadsDaemonsetsNamespaceNameRouteImport.update({
    id: '/workloads/daemonsets/$namespace/$name',
    path: '/workloads/daemonsets/$namespace/$name',
    getParentRoute: () => rootRouteImport,
  } as any);
const WorkloadsDeploymentsNamespaceNameRoute =
  WorkloadsDeploymentsNamespaceNameRouteImport.update({
    id: '/workloads/deployments/$namespace/$name',
    path: '/workloads/deployments/$namespace/$name',
    getParentRoute: () => rootRouteImport,
  } as any);
const WorkloadsJobsNamespaceNameRoute =
  WorkloadsJobsNamespaceNameRouteImport.update({
    id: '/workloads/jobs/$namespace/$name',
    path: '/workloads/jobs/$namespace/$name',
    getParentRoute: () => rootRouteImport,
  } as any);
const WorkloadsPodsNamespaceNameRoute =
  WorkloadsPodsNamespaceNameRouteImport.update({
    id: '/workloads/pods/$namespace/$name',
    path: '/workloads/pods/$namespace/$name',
    getParentRoute: () => rootRouteImport,
  } as any);
const WorkloadsStatefulsetsNamespaceNameRoute =
  WorkloadsStatefulsetsNamespaceNameRouteImport.update({
    id: '/workloads/statefulsets/$namespace/$name',
    path: '/workloads/statefulsets/$namespace/$name',
    getParentRoute: () => rootRouteImport,
  } as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/settings': typeof SettingsRoute;
  '/overview/namespaces': typeof OverviewNamespacesRoute;
  '/overview/nodes': typeof OverviewNodesRoute;
  '/overview/summary': typeof OverviewSummaryRoute;
  '/overview/nodes/$name': typeof OverviewNodesNameRoute;
  '/workloads/autoscalers/': typeof WorkloadsAutoscalersIndexRoute;
  '/workloads/cronjobs/': typeof WorkloadsCronjobsIndexRoute;
  '/workloads/daemonsets/': typeof WorkloadsDaemonsetsIndexRoute;
  '/workloads/deployments/': typeof WorkloadsDeploymentsIndexRoute;
  '/workloads/jobs/': typeof WorkloadsJobsIndexRoute;
  '/workloads/pods/': typeof WorkloadsPodsIndexRoute;
  '/workloads/statefulsets/': typeof WorkloadsStatefulsetsIndexRoute;
  '/workloads/autoscalers/$namespace/$name': typeof WorkloadsAutoscalersNamespaceNameRoute;
  '/workloads/cronjobs/$namespace/$name': typeof WorkloadsCronjobsNamespaceNameRoute;
  '/workloads/daemonsets/$namespace/$name': typeof WorkloadsDaemonsetsNamespaceNameRoute;
  '/workloads/deployments/$namespace/$name': typeof WorkloadsDeploymentsNamespaceNameRoute;
  '/workloads/jobs/$namespace/$name': typeof WorkloadsJobsNamespaceNameRoute;
  '/workloads/pods/$namespace/$name': typeof WorkloadsPodsNamespaceNameRoute;
  '/workloads/statefulsets/$namespace/$name': typeof WorkloadsStatefulsetsNamespaceNameRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/settings': typeof SettingsRoute;
  '/overview/namespaces': typeof OverviewNamespacesRoute;
  '/overview/nodes': typeof OverviewNodesRoute;
  '/overview/summary': typeof OverviewSummaryRoute;
  '/overview/nodes/$name': typeof OverviewNodesNameRoute;
  '/workloads/autoscalers': typeof WorkloadsAutoscalersIndexRoute;
  '/workloads/cronjobs': typeof WorkloadsCronjobsIndexRoute;
  '/workloads/daemonsets': typeof WorkloadsDaemonsetsIndexRoute;
  '/workloads/deployments': typeof WorkloadsDeploymentsIndexRoute;
  '/workloads/jobs': typeof WorkloadsJobsIndexRoute;
  '/workloads/pods': typeof WorkloadsPodsIndexRoute;
  '/workloads/statefulsets': typeof WorkloadsStatefulsetsIndexRoute;
  '/workloads/autoscalers/$namespace/$name': typeof WorkloadsAutoscalersNamespaceNameRoute;
  '/workloads/cronjobs/$namespace/$name': typeof WorkloadsCronjobsNamespaceNameRoute;
  '/workloads/daemonsets/$namespace/$name': typeof WorkloadsDaemonsetsNamespaceNameRoute;
  '/workloads/deployments/$namespace/$name': typeof WorkloadsDeploymentsNamespaceNameRoute;
  '/workloads/jobs/$namespace/$name': typeof WorkloadsJobsNamespaceNameRoute;
  '/workloads/pods/$namespace/$name': typeof WorkloadsPodsNamespaceNameRoute;
  '/workloads/statefulsets/$namespace/$name': typeof WorkloadsStatefulsetsNamespaceNameRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/settings': typeof SettingsRoute;
  '/overview/namespaces': typeof OverviewNamespacesRoute;
  '/overview/nodes': typeof OverviewNodesRoute;
  '/overview/summary': typeof OverviewSummaryRoute;
  '/overview/nodes_/$name': typeof OverviewNodesNameRoute;
  '/workloads/autoscalers/': typeof WorkloadsAutoscalersIndexRoute;
  '/workloads/cronjobs/': typeof WorkloadsCronjobsIndexRoute;
  '/workloads/daemonsets/': typeof WorkloadsDaemonsetsIndexRoute;
  '/workloads/deployments/': typeof WorkloadsDeploymentsIndexRoute;
  '/workloads/jobs/': typeof WorkloadsJobsIndexRoute;
  '/workloads/pods/': typeof WorkloadsPodsIndexRoute;
  '/workloads/statefulsets/': typeof WorkloadsStatefulsetsIndexRoute;
  '/workloads/autoscalers/$namespace/$name': typeof WorkloadsAutoscalersNamespaceNameRoute;
  '/workloads/cronjobs/$namespace/$name': typeof WorkloadsCronjobsNamespaceNameRoute;
  '/workloads/daemonsets/$namespace/$name': typeof WorkloadsDaemonsetsNamespaceNameRoute;
  '/workloads/deployments/$namespace/$name': typeof WorkloadsDeploymentsNamespaceNameRoute;
  '/workloads/jobs/$namespace/$name': typeof WorkloadsJobsNamespaceNameRoute;
  '/workloads/pods/$namespace/$name': typeof WorkloadsPodsNamespaceNameRoute;
  '/workloads/statefulsets/$namespace/$name': typeof WorkloadsStatefulsetsNamespaceNameRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/settings'
    | '/overview/namespaces'
    | '/overview/nodes'
    | '/overview/summary'
    | '/overview/nodes/$name'
    | '/workloads/autoscalers/'
    | '/workloads/cronjobs/'
    | '/workloads/daemonsets/'
    | '/workloads/deployments/'
    | '/workloads/jobs/'
    | '/workloads/pods/'
    | '/workloads/statefulsets/'
    | '/workloads/autoscalers/$namespace/$name'
    | '/workloads/cronjobs/$namespace/$name'
    | '/workloads/daemonsets/$namespace/$name'
    | '/workloads/deployments/$namespace/$name'
    | '/workloads/jobs/$namespace/$name'
    | '/workloads/pods/$namespace/$name'
    | '/workloads/statefulsets/$namespace/$name';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/settings'
    | '/overview/namespaces'
    | '/overview/nodes'
    | '/overview/summary'
    | '/overview/nodes/$name'
    | '/workloads/autoscalers'
    | '/workloads/cronjobs'
    | '/workloads/daemonsets'
    | '/workloads/deployments'
    | '/workloads/jobs'
    | '/workloads/pods'
    | '/workloads/statefulsets'
    | '/workloads/autoscalers/$namespace/$name'
    | '/workloads/cronjobs/$namespace/$name'
    | '/workloads/daemonsets/$namespace/$name'
    | '/workloads/deployments/$namespace/$name'
    | '/workloads/jobs/$namespace/$name'
    | '/workloads/pods/$namespace/$name'
    | '/workloads/statefulsets/$namespace/$name';
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/overview/namespaces'
    | '/overview/nodes'
    | '/overview/summary'
    | '/overview/nodes_/$name'
    | '/workloads/autoscalers/'
    | '/workloads/cronjobs/'
    | '/workloads/daemonsets/'
    | '/workloads/deployments/'
    | '/workloads/jobs/'
    | '/workloads/pods/'
    | '/workloads/statefulsets/'
    | '/workloads/autoscalers/$namespace/$name'
    | '/workloads/cronjobs/$namespace/$name'
    | '/workloads/daemonsets/$namespace/$name'
    | '/workloads/deployments/$namespace/$name'
    | '/workloads/jobs/$namespace/$name'
    | '/workloads/pods/$namespace/$name'
    | '/workloads/statefulsets/$namespace/$name';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  SettingsRoute: typeof SettingsRoute;
  OverviewNamespacesRoute: typeof OverviewNamespacesRoute;
  OverviewNodesRoute: typeof OverviewNodesRoute;
  OverviewSummaryRoute: typeof OverviewSummaryRoute;
  OverviewNodesNameRoute: typeof OverviewNodesNameRoute;
  WorkloadsAutoscalersIndexRoute: typeof WorkloadsAutoscalersIndexRoute;
  WorkloadsCronjobsIndexRoute: typeof WorkloadsCronjobsIndexRoute;
  WorkloadsDaemonsetsIndexRoute: typeof WorkloadsDaemonsetsIndexRoute;
  WorkloadsDeploymentsIndexRoute: typeof WorkloadsDeploymentsIndexRoute;
  WorkloadsJobsIndexRoute: typeof WorkloadsJobsIndexRoute;
  WorkloadsPodsIndexRoute: typeof WorkloadsPodsIndexRoute;
  WorkloadsStatefulsetsIndexRoute: typeof WorkloadsStatefulsetsIndexRoute;
  WorkloadsAutoscalersNamespaceNameRoute: typeof WorkloadsAutoscalersNamespaceNameRoute;
  WorkloadsCronjobsNamespaceNameRoute: typeof WorkloadsCronjobsNamespaceNameRoute;
  WorkloadsDaemonsetsNamespaceNameRoute: typeof WorkloadsDaemonsetsNamespaceNameRoute;
  WorkloadsDeploymentsNamespaceNameRoute: typeof WorkloadsDeploymentsNamespaceNameRoute;
  WorkloadsJobsNamespaceNameRoute: typeof WorkloadsJobsNamespaceNameRoute;
  WorkloadsPodsNamespaceNameRoute: typeof WorkloadsPodsNamespaceNameRoute;
  WorkloadsStatefulsetsNamespaceNameRoute: typeof WorkloadsStatefulsetsNamespaceNameRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/settings': {
      id: '/settings';
      path: '/settings';
      fullPath: '/settings';
      preLoaderRoute: typeof SettingsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/overview/namespaces': {
      id: '/overview/namespaces';
      path: '/overview/namespaces';
      fullPath: '/overview/namespaces';
      preLoaderRoute: typeof OverviewNamespacesRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/overview/nodes': {
      id: '/overview/nodes';
      path: '/overview/nodes';
      fullPath: '/overview/nodes';
      preLoaderRoute: typeof OverviewNodesRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/overview/summary': {
      id: '/overview/summary';
      path: '/overview/summary';
      fullPath: '/overview/summary';
      preLoaderRoute: typeof OverviewSummaryRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/overview/nodes_/$name': {
      id: '/overview/nodes_/$name';
      path: '/overview/nodes/$name';
      fullPath: '/overview/nodes/$name';
      preLoaderRoute: typeof OverviewNodesNameRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/workloads/autoscalers/': {
      id: '/workloads/autoscalers/';
      path: '/workloads/autoscalers';
      fullPath: '/workloads/autoscalers/';
      preLoaderRoute: typeof WorkloadsAutoscalersIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/workloads/cronjobs/': {
      id: '/workloads/cronjobs/';
      path: '/workloads/cronjobs';
      fullPath: '/workloads/cronjobs/';
      preLoaderRoute: typeof WorkloadsCronjobsIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/workloads/daemonsets/': {
      id: '/workloads/daemonsets/';
      path: '/workloads/daemonsets';
      fullPath: '/workloads/daemonsets/';
      preLoaderRoute: typeof WorkloadsDaemonsetsIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/workloads/deployments/': {
      id: '/workloads/deployments/';
      path: '/workloads/deployments';
      fullPath: '/workloads/deployments/';
      preLoaderRoute: typeof WorkloadsDeploymentsIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/workloads/jobs/': {
      id: '/workloads/jobs/';
      path: '/workloads/jobs';
      fullPath: '/workloads/jobs/';
      preLoaderRoute: typeof WorkloadsJobsIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/workloads/pods/': {
      id: '/workloads/pods/';
      path: '/workloads/pods';
      fullPath: '/workloads/pods/';
      preLoaderRoute: typeof WorkloadsPodsIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/workloads/statefulsets/': {
      id: '/workloads/statefulsets/';
      path: '/workloads/statefulsets';
      fullPath: '/workloads/statefulsets/';
      preLoaderRoute: typeof WorkloadsStatefulsetsIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/workloads/autoscalers/$namespace/$name': {
      id: '/workloads/autoscalers/$namespace/$name';
      path: '/workloads/autoscalers/$namespace/$name';
      fullPath: '/workloads/autoscalers/$namespace/$name';
      preLoaderRoute: typeof WorkloadsAutoscalersNamespaceNameRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/workloads/cronjobs/$namespace/$name': {
      id: '/workloads/cronjobs/$namespace/$name';
      path: '/workloads/cronjobs/$namespace/$name';
      fullPath: '/workloads/cronjobs/$namespace/$name';
      preLoaderRoute: typeof WorkloadsCronjobsNamespaceNameRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/workloads/daemonsets/$namespace/$name': {
      id: '/workloads/daemonsets/$namespace/$name';
      path: '/workloads/daemonsets/$namespace/$name';
      fullPath: '/workloads/daemonsets/$namespace/$name';
      preLoaderRoute: typeof WorkloadsDaemonsetsNamespaceNameRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/workloads/deployments/$namespace/$name': {
      id: '/workloads/deployments/$namespace/$name';
      path: '/workloads/deployments/$namespace/$name';
      fullPath: '/workloads/deployments/$namespace/$name';
      preLoaderRoute: typeof WorkloadsDeploymentsNamespaceNameRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/workloads/jobs/$namespace/$name': {
      id: '/workloads/jobs/$namespace/$name';
      path: '/workloads/jobs/$namespace/$name';
      fullPath: '/workloads/jobs/$namespace/$name';
      preLoaderRoute: typeof WorkloadsJobsNamespaceNameRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/workloads/pods/$namespace/$name': {
      id: '/workloads/pods/$namespace/$name';
      path: '/workloads/pods/$namespace/$name';
      fullPath: '/workloads/pods/$namespace/$name';
      preLoaderRoute: typeof WorkloadsPodsNamespaceNameRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/workloads/statefulsets/$namespace/$name': {
      id: '/workloads/statefulsets/$namespace/$name';
      path: '/workloads/statefulsets/$namespace/$name';
      fullPath: '/workloads/statefulsets/$namespace/$name';
      preLoaderRoute: typeof WorkloadsStatefulsetsNamespaceNameRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  OverviewNamespacesRoute: OverviewNamespacesRoute,
  OverviewNodesRoute: OverviewNodesRoute,
  OverviewSummaryRoute: OverviewSummaryRoute,
  OverviewNodesNameRoute: OverviewNodesNameRoute,
  WorkloadsAutoscalersIndexRoute: WorkloadsAutoscalersIndexRoute,
  WorkloadsCronjobsIndexRoute: WorkloadsCronjobsIndexRoute,
  WorkloadsDaemonsetsIndexRoute: WorkloadsDaemonsetsIndexRoute,
  WorkloadsDeploymentsIndexRoute: WorkloadsDeploymentsIndexRoute,
  WorkloadsJobsIndexRoute: WorkloadsJobsIndexRoute,
  WorkloadsPodsIndexRoute: WorkloadsPodsIndexRoute,
  WorkloadsStatefulsetsIndexRoute: WorkloadsStatefulsetsIndexRoute,
  WorkloadsAutoscalersNamespaceNameRoute:
    WorkloadsAutoscalersNamespaceNameRoute,
  WorkloadsCronjobsNamespaceNameRoute: WorkloadsCronjobsNamespaceNameRoute,
  WorkloadsDaemonsetsNamespaceNameRoute: WorkloadsDaemonsetsNamespaceNameRoute,
  WorkloadsDeploymentsNamespaceNameRoute:
    WorkloadsDeploymentsNamespaceNameRoute,
  WorkloadsJobsNamespaceNameRoute: WorkloadsJobsNamespaceNameRoute,
  WorkloadsPodsNamespaceNameRoute: WorkloadsPodsNamespaceNameRoute,
  WorkloadsStatefulsetsNamespaceNameRoute:
    WorkloadsStatefulsetsNamespaceNameRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
