/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as IndexRouteImport } from './routes/index';
import { Route as OverviewNamespacesRouteImport } from './routes/overview/namespaces';
import { Route as OverviewNodesRouteImport } from './routes/overview/nodes';
import { Route as OverviewSummaryRouteImport } from './routes/overview/summary';

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const OverviewNamespacesRoute = OverviewNamespacesRouteImport.update({
  id: '/overview/namespaces',
  path: '/overview/namespaces',
  getParentRoute: () => rootRouteImport,
} as any);
const OverviewNodesRoute = OverviewNodesRouteImport.update({
  id: '/overview/nodes',
  path: '/overview/nodes',
  getParentRoute: () => rootRouteImport,
} as any);
const OverviewSummaryRoute = OverviewSummaryRouteImport.update({
  id: '/overview/summary',
  path: '/overview/summary',
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/overview/namespaces': typeof OverviewNamespacesRoute;
  '/overview/nodes': typeof OverviewNodesRoute;
  '/overview/summary': typeof OverviewSummaryRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/overview/namespaces': typeof OverviewNamespacesRoute;
  '/overview/nodes': typeof OverviewNodesRoute;
  '/overview/summary': typeof OverviewSummaryRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/overview/namespaces': typeof OverviewNamespacesRoute;
  '/overview/nodes': typeof OverviewNodesRoute;
  '/overview/summary': typeof OverviewSummaryRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    '/' | '/overview/namespaces' | '/overview/nodes' | '/overview/summary';
  fileRoutesByTo: FileRoutesByTo;
  to: '/' | '/overview/namespaces' | '/overview/nodes' | '/overview/summary';
  id:
    | '__root__'
    | '/'
    | '/overview/namespaces'
    | '/overview/nodes'
    | '/overview/summary';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  OverviewNamespacesRoute: typeof OverviewNamespacesRoute;
  OverviewNodesRoute: typeof OverviewNodesRoute;
  OverviewSummaryRoute: typeof OverviewSummaryRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/overview/namespaces': {
      id: '/overview/namespaces';
      path: '/overview/namespaces';
      fullPath: '/overview/namespaces';
      preLoaderRoute: typeof OverviewNamespacesRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/overview/nodes': {
      id: '/overview/nodes';
      path: '/overview/nodes';
      fullPath: '/overview/nodes';
      preLoaderRoute: typeof OverviewNodesRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/overview/summary': {
      id: '/overview/summary';
      path: '/overview/summary';
      fullPath: '/overview/summary';
      preLoaderRoute: typeof OverviewSummaryRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OverviewNamespacesRoute: OverviewNamespacesRoute,
  OverviewNodesRoute: OverviewNodesRoute,
  OverviewSummaryRoute: OverviewSummaryRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
